### PR TITLE
A better API for collections

### PR DESCRIPTION
**Pull request by HerbCaudill**
The API has ended up looking pretty different from what was originally proposed; see below for details. The original proposal is here for reference. 

<details>
  <summary>Original proposal</summary>

### Why do we have collections in the first place?

At first we were using a single Automerge document to store everything, and the API was very simple: You just figured out a JSON structure for your entire state and passed it in. So, for example:

```js
const state = {
  settings: {...},
  teachers: {
    abc123: {...},
    qrs666: {...},
  },
  students: {
    def987: {...},
    xyz007: {...},
  },
}
```

The problem was that no individual document can support hundreds of thousands of anything. In order to be able to scale, we switched to using multiple Automerge documents in a DocSet. So anything that you might have "a lot of" had to live at the root. Our first attempt looked something like this:

```js
const state = {
  settings: {...},
  teachers: ['abc123', 'qrs666'],
  students: ['def987', 'xyz007'],
  abc123: {...},
  qrs666: {...},
  def987: {...},
  xyz007: {...},
}
```

This worked, but the index documents `teachers` and `students` were still problematic: Even a document containing nothing but an array of keys would use up the whole Javascript heap at some point between 100K and 1M items.

So we came up with a scheme that used a naming convention to keep collections separate without requiring an index - something like this:

```js
const state = {
  settings: {...},
  teacher_abc123: {...},
  teacher_qrs666: {...},
  student_def987: {...},
  student_xyz007: {...},
}
```

This also worked, but now we have to write a lot of code to do simple things like

- get a list of all items in a collection
- convert an item's ID (e.g. `abc123`) to the collection key (e.g. `teacher_abc123`) and vice-versa
- delete an item

Deleting items in particular was tricky without an index: We want deletions to replicate across peers, but without an index, we had to come up with a complicated scheme involving a magical `__DELETED` property.

The `collection` object wraps that complexity by providing helpers for CRUD functions. In reducers, you can do this:

```ts
const { add, update, remove, drop } = collection('rows').reducers
switch (type) {
  case actions.ITEM_ADD:
    return add(payload)
  case actions.ITEM_UPDATE:
    return update(payload)
  case actions.ITEM_REMOVE:
    return remove(payload)
  case actions.COLLECTION_CLEAR:
    return drop()
  // ...
}
```

To access the items in a collection, you have selectors that will give them to you as an array or as a map:

```ts
const rowArray = collection('rows').selectors.getAll(state)
const rowMap = collection('rows').selectors.getMap(state)
```

### What don't we like about this?

This entire API came from the requirement to handle datasets too large to fit into browser memory.

But many applications (most applications?) don't involve huge datasets, and can benefit from the simplicity that comes from having the entire application's state in a single in-memory JSON object. For these use cases, the current API is really cumbersome. (See also #40.)

I also worry that we're drifting farther and farther the standard Redux API that developers are likely to be familiar with.

Even in applications that _do_ have multiple large collections, this API feels awkward. Every time I come back to it I have to re-read the docs I wrote earlier. I think we can make the DX for this use case a little more ergonomic without making big changes.

### Why do we have more options now than when we created this interface?

We created this setup to work within the limitations of an `Automerge.DocSet`. This is a very simple in-memory key/value structure that contains Automerge documents and fires events when any document is added or changed.

We now use the `Repo` object, which is basically a `DocSet` that takes a storage adapter to persist its contents. Rather than dealing directly with Automerge documents all the time, a `Repo` manages change histories, vector clocks, and snapshots, only rehydrating an Automerge document when necessary.

Since we no longer need to represent all our data as root-level items in a `DocSet`, we can rethink this API so that it handles both use cases - simple in-memory state and large datasets - without developer headaches.

### What might a better interface look like?

In my ideal world, we can go back to something more like a plain-vanilla Redux API. A developer can structure their state document in a familiar way, and just indicate which elements need the "collections" treatment when initializing the store. Something like this:

```ts
const initialState = {
  settings: { schoolName: 'My new school', defaultTheme: 'dark' },
  teachers: {}, // <-- every teacher will be a separate Automerge doc, but I don't need to think about that
  students: {}, // <-- same deal with students
}

export const storeManager = new StoreManager({
  databaseName: 'school',
  collections: ['teachers', 'students'], // <-- I just have to indicate what needs to be treated as collections
  proxyReducer,
  initialState,
})
```

#### Regular objects

For anything that isn't part of a collection, the API is straight-up Redux.

##### Selectors

```ts
const defaultTheme = useSelector(state => state.settings.defaultTheme)
```

##### Reducers

Reducers still [use Automerge change functions](http://github.com/DevResults/cevitxe#proxy-reducers-for-automerge-are-different-from-ordinary-redux-reducers) instead of standard Redux pure functions, but we can just return a single function instead of a dictionary of functions:

```ts
case actions.CHANGE_DEFAULT_THEME:
  return state => state.defaultTheme = payload
//...
```

##### Selectors

To read data from collections, we use the `collection.selectors` function, which takes a state object and returns a dictionary of collections. Each one of these offers an interface designed to mimic an ES6 `Map`, but with asynchronous accessors:

```ts
const { teachers } = collection.selectors(state)

// get a single record
const teacher = await teachers.get(id)

// check for existence of a record
if (await teachers.has(id)) {
  //...
}

// count records
const n = await teachers.size

// loop through keys
for await (const id of teachers.keys()) {
  //...
}

// loop through values
for await (const teacher of teachers.values()) {
  //...
}
```

##### Reducers

Since each item in a collection is a separate Automerge document, the reducers for collection items still need to return a dictionary of functions, keyed to the item id (the way they do now).

We can do this by hand:

```ts
case actions.UPDATE_TEACHER:
  const { id, teacher } = payload
  return {
    id: s => ({...s, ...teacher})
  }
```

Or we can use helpers provided by the `collection` object:

```ts
const { teachers } = collection.reducers(state)
switch (type) {
  case actions.UPDATE_TEACHER:
    return teachers.update(payload)
  //...
}
```

#### Implementation

The `StorageAdapter` abstract class will need to change to be collection-aware. I was thinking something like this:

```ts
export interface SnapshotRecord {
  documentId: string
  collection: string // <-- new
  snapshot: Snapshot
  clock: Clock
}

export interface ChangeSet {
  documentId: string
  collection: string // <-- new
  changes: A.Change[]
}

type ChangeSetIterator = AsyncIterableIterator<IteratorResult<ChangeSet, ChangeSet>>
type SnapshotIterator = AsyncIterableIterator<IteratorResult<SnapshotRecord, SnapshotRecord>>

export abstract class StorageAdapter {
  storageKey: string

  constructor(options: {
    discoveryKey: string
    databaseName: string
    collections?: string[] // <-- new
  }) {}

  abstract async open(): Promise<void>
  abstract async close(): Promise<void>

  abstract async hasData(): Promise<boolean>

  abstract changes(collection?: string): ChangeSetIterator // <-- new optional parameter
  abstract snapshots(collection?: string): SnapshotIterator // <-- new optional parameter

  abstract async getChanges(documentId: string): Promise<ChangeSet[]>
  abstract async appendChanges(changeSet: ChangeSet): Promise<void>

  abstract async putSnapshot(snapshotRecord: SnapshotRecord): Promise<void>
  abstract async deleteSnapshot(documentId: string): Promise<void>
}
```

The underlying implementation of collections will be up to each individual storage adapter. For example, for the `IdbAdapter`, here are some options we might consider:

1. create separate `changes` and `snapshots` object stores for each collection, e.g. `changes_teachers` and `snapshots_teachers`
2. store each collection in a separate database
3. leave everything jumbled up together, but persist special collection index documents indicating which documents belong to which collections
4. store everything in the existing `changes` and `snapshots` object stores, and add an indexed `collection` field to the containing record
5. ... etc.

I'd probably lean towards option 4 for IndexedDB, but different approaches will make sense for different persistence technologies. The point is that at the API level we don't need to care about the implementation details.

</detail>

### CODE REVIEW

**Comment by brentkeller** [comment]
I've been out of cevitxe for 2 months now so I'm a bit foggy on things and pretty much unaware of the snapshots, but what you're proposing sounds pretty good for the most part. It seems to me that designating things as a collection via a separate list property feels "icky". I know it moves away from the "vanilla Redux API" (but let's be honest, we're making people build reducers a certain way anyway) but I think it might be useful to register a schema for the state. I'm picturing something similar to the [model schemas in mongoose](https://mongoosejs.com/docs/guide.html) but perhaps where you could also describe the default (initial) value for something.

A possible example could be like this:
```
import { Schema, String, Number } from 'cevitxe'

const initialState = new Schema({
  settings: { 
    schoolName: String('My new school'),
	defaultTheme: String('dark')
  },
  teachers: [{
	id: Number(),
	firstName: String(),
	lastName: String(),
  }],
  students: [{
	id: Number(),
	firstName: String(),
	lastName: String(),
  }],
})
```

Maybe all the property types aren't that important (or even need to be declared) other than if a root-level property is of type `Array` then it will be treated as a collection in cevitxe, which abstracts the implementation details and provides helpers for `get`, `list`, etc....  I'm not sure we would, but if we feel there is a distinct difference between exposing a thing as an array vs a map, we could introduce types for those (like `String` and `Number` in mongoose) and find a way to designate those as part of the definition.

I agree with trying to keep things as simple and vanilla as possible but I think that consumers would be willing to pay a bit of configuration cost up front to get the benefits our framework is providing. Anyway, I wanted to suggest an alternative that feels similar to what other data access libraries offer and devs might find familiar.

**Comment by HerbCaudill** [comment]
OK. This has ended up looking different from what I described above, but I think it's a lot better.

There are two bits of awkwardness that we're trying to paper here:

1. As described above, Automerge's overhead makes it inefficient to deal with very large arrays. So rather than treat a single Automerge document as our root entity, we have a Repo that deals with any number of Automerge documents.

2. If we do that, though, we run into the issue that scalars and arrays can't be turned into Automerge documents; an Automerge document _always_ represents an object.

Take a simplified todo data structure:

```js
// "natural" state (used by application)
{
visibilityFilter: 'all',
todos: {
  abc123: { content: 'Brush teeth', completed: false },
  qrs666: { content: 'Make bed', completed: false },
},
```

Here `visibilityFilter` (a scalar) can't be a free-standing Automerge document. So it needs to be wrapped in some kind of container.

The storage structure that we need - I'm calling this the "normalized" state - looks like this:

```js
// "normalized" state (for storage and synchronization)
const normalizedState = {
  __global: { visibilityFilter: 'all' }, // Automerge doc
  __todos__abc123: { id: 'abc123', content: 'Brush teeth', completed: false }, // Automerge doc
  __todos__qrs666: { id: 'qrs666', content: 'Make bed', completed: false }, // Automerge doc
}
```

But we don't want the developer to ever have to see this nastiness or think about it. So we accept the "natural" or "denormalized" form when setting `initialState` for a repo, and we normalize it; when we return state to the application via `repo.getState()`, we denormalize it.

### No more selector helpers

This eliminates the need for our collection selector helpers; since state is denormalized before we ever see it, we can work directly with items in collections, like this:

```js
const thisTeacher = useSelector(state => state.teachers[id])
```

Tada!

### No more reducer helpers

We still need some help with reducers, since we need one change function per Automerge document being modified. But rather than expose helpers for every situation we can think of (so far, we had `add`, `update`, `change`, `delete`, and `drop`), we define a simple format for passing metadata (collection name and item id) along with the change function.

So for example in the grid app, the `ITEM_UPDATE` reducer looks like this:

```js
case actions.ITEM_UPDATE: {
  const updatedRow = payload
  const { id } = updatedRow
  const fn = (row: any) => {
    Object.assign(row, updatedRow)
  }
  return { collection, id, fn }
}
```

Now the only class that needs to know anything about how collections are implemented is `Repo`. (Not the storage adapters, as I was originally thinking. This is a slightly higher-level concern, since the `Connection` also needs to work with the normalized multi-document data structure.)

Also, this cleans up our API surface nicely. We only expose one thing to the developer: `StoreManager`.

Here's the full API docs from `getting-started.md`:

---

#### Collections

By default, your state is stored in a single Automerge document.

However, a limitation of Automerge is that [no individual document can support hundreds of thousands of anything](http://github.com/automerge/automerge/issues/89).

If you're likely to have "a lot of" some _thing_ in your application, you can create a **collection** of those _things_. Internally, each one of those items will be treated as an individual Automerge document.

Suppose your state includes a map of teachers, and another of students.

```js
{
  settings: { schoolName: 'My new school', defaultTheme: 'dark' },
  teachers: {
    def987: { id: 'def987', name: 'Marvin', ... }
    xyz007: { id: 'xyz007', name: 'Juanita', ... }
  },
  students: {
    abc123: { id: 'abc123', name: 'Herb', ... }
    qrs666: { id: 'qrs666', name: 'Brent', ... }
  },
}
```

If we think that we might have a large number of `teachers` and `students`, we can mark both of those as collections:

```js
export const storeManager = new StoreManager({
  databaseName: 'school',
  collections: ['teachers', 'students'],
  proxyReducer,
  initialState,
})
```

> The data in collections must look like the example above. Specifically:
>
> - The **collection** must be in the form of an object that maps identifiers to records. (It can't be an array.)
> - Each **item** in a collection must be an object. (Not a scalar, not an array.)
> - Each item must include its **unique identfier** as an `id` property.
> - The collections must live at the **root** of your state. (They can't be nested under another object.)

##### Collection selectors

To **read** from anything in a collection, your selectors don't change: you can just access the map directly.

```ts
const thisTeacher = useSelector(state => state.teachers[id])
```

##### Collection reducers

To **write** to a collection in a reducer, rather than returning a change function, you return one or more change functions, each wrapped in an object containing metadata.

###### Creating and updating

To add or update items in collections, instead of returning just a function, you return one or more change manifests of this form:

```js
{
    collection, // the name of the collection
    id, // the id of the item in the collection
    fn, // the change function
}
```

Some examples:

```js
case ADD_TEACHER: {
    const newTeacher = payload
    const { id } = newTeacher
    // return change function with metadata
    return {
        collection: 'teachers',
        id,
        fn: teacher => {
          Object.assign(teacher, newTeacher) // here `s` is `{}`
        }
    }
}
case ADD_TEACHERS: {
	const newTeachers = payload // array of objects to add
    // return array of change functions with metadata
    return newTeachers.map(newTeacher => ({
        collection: 'teachers',
        id,
        fn: teacher => {
          Object.assign(teacher, newTeacher)
        }
    }))
}
case UPDATE_TEACHER: {
    const updatedTeacher = payload // object with data to modify
    const { id } = updatedTeacher
    // return change function with metadata
    return {
        collection: 'teachers',
        id,
        fn: teacher => {
          Object.assign(teacher, updatedTeacher)
        }
    }
}
```

###### Deleting

To delete an item from a collection, return an object of this form:

```js
{
    collection, // the name of the collection
    id, // the id of the item to delete
	delete: true // special flag
}
```

Example:

```js
case DELETE_TEACHER: {
    const { id } = payload.id
    // return delete flag
    return {
        collection: 'teachers',
        id,
        delete: true
    }
}
```

To delete all items from a collection, return an object of this form:

```js
{
    collection, // the name of the collection
	drop: true // special flag
}
```

Example:

```js
case DROP_TEACHERS: {
    // return drop flag
    return {
        collection: 'teachers',
        drop: true
    }
}
```

###### Combining different types of reducers

You might need a reducer that changes collection data as well as non-collection data. For example, in the grid example, [this reducer](https://github.com/DevResults/cevitxe/blob/68d89dd3d11b4a134b9ca0408eef6ab6978d3b3f/packages/cevitxe-example-grid/src/redux/reducers.ts#L75-L93) modifies a global schema object to delete a field, and then deletes the corresponding data from each row.

In this case you can return an array that combines change functions (for the global changes) and change manifests (for the changes to collection items).

```js
case actions.FIELD_DELETE: {
  const { id: fieldId } = payload

  // remove field from schema
  const schemaChange = s => {
    delete s.schema.properties![fieldId]
  }

  // change function: delete the value from one row
  const fn = row => {
    delete row[fieldId]
  }

  const rowIds = Object.keys(state.rows)
  const rowChanges = rowIds.map(id => ({ collection, id, fn }))

  return [schemaChange, ...rowChanges]
}
```

**Comment by brentkeller** [comment]
@HerbCaudill  This all looks good and I'm happy to see less fiddling involved with using cevitxe. I'm curious if we need some additional markers on the provided state to indicate which things should be persisted/synced to the remote instances. For instance, you might want to exclude the `ui` section of the state in [this example from the redux docs](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape#organizing-normalized-data-in-state).

A potential solution could look like the whitelist/blacklist config used in [redux-persist](https://github.com/rt2zz/redux-persist#blacklist--whitelist).

Something to think about, I think we'll want to allow the flexibility of consumers putting things in their redux store but not being transmitted to all replicas (e.g. UI filter selections, etc.).

**Comment by HerbCaudill** [comment]
yeah, that's true, and I think redux persist's whitelist/blacklist approach is probably good. I'll make a separate issue for that.

**Pull request merged**
